[[plugins]]  
package = "@netlify/plugin-lighthouse"  

[[plugins]]  
package = "@netlify/plugin-image-optim"  
  [plugins.inputs]
	formats = ["webp", "original"]  
	compress = true  
	lazy = true  
